### ISSUE TITLE
Game Error

### ISSUE THREAD

**Issue by AgaricaGamer** [boi1216/BedWars-Rewrite#1]
![Uploading Screenshot_20210123_130143.png…]()

**Comment by QMoon10189** [comment]
It says uploading

**Comment by AgaricaGamer** [comment]
How do i fix that?

I need the plugin to play with my friends on local!

**Comment by QMoon10189** [comment]
Use his bedwars old version

**Comment by QMoon10189** [comment]
At poggit have many fixed plugin

**Comment by boi1216** [comment]
Working on new version
